org: serezha
app: http-app
service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  else:
    handler: handler.else
    events:
      - http:
          path: /else
          method: get
  addCar:
    handler: handler.addCar
    events:
      - http:
          path: /addCar
          method: post

resources:
  Resources:
    Car:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Car
        AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        KeySchema:
        - AttributeName: user
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Models:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Models
        AttributeDefinitions:
          - AttributeName: Brand
            AttributeType: S
          - AttributeName: Model
            AttributeType: S
        KeySchema:
          - AttributeName: Brand
            KeyType: HASH
          - AttributeName: Model
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: login
            AttributeType: S
        KeySchema:
          - AttributeName: login
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack

