org: serezha
app: http-app
service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  addCar:
    handler: handler.addCar
    events:
      - http:
          path: /addCar
          method: post

  getUserCars:
    handler: handler.getUserCars
    events:
      - http:
          path: /getUserCars
          method: post

  getModelsByBrand:
    handler: handler.getModelsByBrand
    events:
      - http:
          path: /getModelsByBrand
          method: post

  getBrands:
    handler: handler.getBrands
    events:
      - http:
          path: /getBrands
          method: get

  updateCar:
    handler: handler.updateCar
    events:
      - http:
          path: /updateCar
          method: post
  getCarById:
    handler: handler.getCarById
    events:
      - http:
          path: /getCarById
          method: post


resources:
  Resources:
    Carsnor:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Carsnor
        AttributeDefinitions:
        - AttributeName: login
          AttributeType: S
        - AttributeName: car_id
          AttributeType: S
        KeySchema:
        - AttributeName: login
          KeyType: HASH
        - AttributeName: car_id
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Modelsnor:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Modelsnor
        AttributeDefinitions:
          - AttributeName: Brand
            AttributeType: S
          - AttributeName: Model
            AttributeType: S
        KeySchema:
          - AttributeName: Brand
            KeyType: HASH
          - AttributeName: Model
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Usersnor:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Usersnor
        AttributeDefinitions:
          - AttributeName: login
            AttributeType: S
        KeySchema:
          - AttributeName: login
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Brandsnor:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Brandsnor
        AttributeDefinitions:
          - AttributeName: brand
            AttributeType: S
        KeySchema:
          - AttributeName: brand
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack
  - serverless-offline

